#!/usr/bin/env /bin/bash

set -euo pipefail

PROJECT=${PROJECT:-$(basename $PWD)}
DOCKER_REPO_OWNER=${DOCKER_REPO_OWNER:-}

LIB_DIR=${LIB_DIR:=.builder}
LIB_REPO=${LIB_REPO:-https://o-p-n/image-builder.git}

function check_prereqs() {
  if [[ -z "${DOCKER_REPO_OWNER}" ]] ; then
    echo "a Docker repo owner must be defined in the env var \$DOCKER_REPO_OWNER"
    return 1
  fi

  if [[ -e "${LIB_DIR}" ]] ; then
    echo "the builder library directory ${LIB_DIR} already exists"
    return 2
  fi
}

function clone_libdir() {
  git clone ${LIB_REPO} ${LIB_DIR}
}

function exclude_libdir() {
  cat << ---EOF--- >> .gitignore
/${LIB_DIR}
---EOF---
  local ignored=$(cat .gitignore | sort | uniq | sed -e 's/^$//')
  echo "${ignored}" > .gitignore
}

function setup_make() {
  cat << ---EOF--- > Makefile
PROJECT=${PROJECT}
DOCKER_REPO_OWNER=${DOCKER_REPO_OWNER}

include ${LIB_DIR}/main.mk

image: ${DOCKER_REPO_OWNER}/${PROJECT}

${DOCKER_REPO_OWNER}/${PROJECT}: Dockerfile
---EOF---
}

check_prereqs
clone_libdir
exclude_libdir
setup_make